# Generated by Django 3.2.4 on 2021-09-30 15:42

import auto_changelog.models.changelog
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('reference', models.TextField(null=True)),
                ('calling_user', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChangelogExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('changelog', models.ManyToManyField(to='auto_changelog.Changelog')),
            ],
            bases=(models.Model, auto_changelog.models.changelog.ChangelogModelMixin),
        ),
    ]
