# Generated by Django 3.2.16 on 2022-11-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_changelog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='changelog',
            index=models.Index(fields=['reference'], name='auto_change_referen_6f6e62_idx'),
        ),
    ]
